<?php

/**
 * Uninstall Handler
 *
 * Fired when the plugin is uninstalled via WordPress admin.
 * Cleans up all plugin data from the database.
 */

// Exit if accessed directly or not called by WordPress
if (!defined('WP_UNINSTALL_PLUGIN')) {
    exit;
}

// Delete plugin options
delete_option('rr_image_alt_settings');

// Delete all alt text generated by this plugin (optional - commented out by default)
// Uncomment the lines below if you want to remove all alt text when plugin is deleted
/*
global $wpdb;
$wpdb->query("DELETE FROM {$wpdb->postmeta} WHERE meta_key = '_wp_attachment_image_alt'");
*/

// Drop the batch jobs table
global $wpdb;
$table_name = $wpdb->prefix . 'rr_alt_batches';
$wpdb->query("DROP TABLE IF EXISTS `{$table_name}`");